feature:
  - all:
    - changed-files: 
      - any-glob-to-any-file:
        - 'src/**/*'
    - head-branch:
      - '^feature/.*'

fix:
  - all:
    - changed-files: 
      - any-glob-to-any-file:
        - 'src/**/*'
    - head-branch:
      - '^fix/.*'

test:
  - any:
    - changed-files: 
      - any-glob-to-any-file:
        - 'test/**/*'
    - head-branch:
      - '^test/.*'

docs:
  - any:
    - changed-files: 
      - any-glob-to-any-file:
        - 'docs/**/*'
    - head-branch:
      - '^docs/.*'

ci:
  - any:
    - changed-files: 
      - any-glob-to-any-file:
        - '.github/**/*'
    - head-branch:
      - '^ci/.*'

config:
  - any:
    - changed-files: 
      - any-glob-to-any-file:
        - '*config*'
    - head-branch:
      - '^config/.*'
