changelog:
  categories:
    - title: ⚠️ Breaking
      labels:
        - breaking
    - title: 🚀 New Features
      labels:
        - feature
    - title: 🪛 Fixes
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"
