name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Bump Package Version
        run: "sed 's/\"version\": \"[0-9]*.[0-9]*.[0-9]*\"/\"version\": \"${{ github.event.release.tag_name }}\"/' package.json"
      - name: Update package.json
        run: |
          git config user.name "Version Bump Bot"
          git config user.email "<>"
          git add package.json 
          git commit -m 'bump package version ${{ github.event.release.tag_name }}'
          git push origin HEAD
      - name: Build Package
        run: |
          npm ci
          npm build
      - uses: actions/upload-artifact@v4
        with:
          name: vanilla-tabs-package 
          path: ./gmvrpw-math-*
          overwrite: true

  publish-github-packages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Setup NPM Registry (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: vanilla-tabs-package 
      - name: Publish Package
        run: npm publish gmvrpw-math-* --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

