name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Bump Package Version
        id: semver_extractor
        uses: actions/github-script@v7
        with:
          script: |
            if ("${{ github.event.release.tag_name }}".match(/v[0-9]+\.[0-9]+\.[0-9]+/)) {
              core.setFailed('Invalid format of release tag');
              return "";
            }
            return "${{ github.event.release.tag_name }}".substring(1)
          result-encoding: string
      - run: sed -i 's/\("version":\) "[0-9]\+\.[0-9]\+\.[0-9]\+"/\1 "${{ steps.semver_extractor.outputs.result }}"/' package.json
      
      - name: Push package.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add package.json 
          git commit -m 'bump version to ${{ steps.semver_extractor.outputs.result }}'
          git push -f
          
      - name: Build & Pack Package
        run: |
          npm ci
          npm run build
          npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: vanilla-tabs-package 
          path: ./gmvrpw-math-*
          overwrite: true

  publish-github-packages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Setup NPM Registry (GitHub Packages)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: vanilla-tabs-package 
      - name: Publish Package
        run: npm publish gmvrpw-math-* --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

